---
- hosts: prometheus
  connection: local 
  become: true
  become_method: sudo
  tasks:
  - name: Add host names
    lineinfile:
      dest: /etc/hosts
      line: '{{ item }}'
    with_items:
      - '10.10.0.101 worker'
      - '10.10.0.100 kafka'
  - name: Download Prometheus
    get_url: 
      url: https://github.com/prometheus/prometheus/releases/download/v1.7.1/prometheus-1.7.1.linux-amd64.tar.gz
      dest: /tmp/prometheus-1.7.1.linux-amd64.tar.gz
  - name: Create Prometheus directory
    file: 
      path: /opt/prometheus 
      state: directory
  - name: Unpack Prometheus
    unarchive: 
      src: /tmp/prometheus-1.7.1.linux-amd64.tar.gz 
      dest: /opt/prometheus/
      copy: no 
      extra_opts: [--strip-components=1]
  - name: Replace Prometheus config
    copy: 
      src: /vagrant/prometheus.yml
      dest: /opt/prometheus/prometheus.yml
      force: yes
  - name: Download node_exporter
    get_url: 
      url: https://github.com/prometheus/node_exporter/releases/download/0.11.0/node_exporter-0.11.0.linux-amd64.tar.gz
      dest: /tmp/node_exporter-0.11.0.linux-amd64.tar.gz
  - name: Create node_exporter directory
    file: 
      path: /opt/prometheus/node_exporter 
      state: directory
  - name: Unpack node_exporter
    unarchive: 
      src: /tmp/node_exporter-0.11.0.linux-amd64.tar.gz
      dest: /opt/prometheus/node_exporter
      copy: no
  - name: Node_exporter service file
    copy: 
      src: /vagrant/node_exporter.service 
      dest: /etc/systemd/system/node_exporter.service
      force: yes
  - name: Start node_exporter
    systemd: 
      name: node_exporter
      state: reloaded 
      enabled: yes 
      daemon-reload: yes
  - name: Wait
    wait_for:
      timeout: 15
  - name: Disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: false
  - name: Prometheus service file
    copy: 
      src: /vagrant/prometheus.service 
      dest: /etc/systemd/system/prometheus.service
      force: yes
  - name: Start prometheus
    systemd: 
      name: prometheus
      state: reloaded 
      enabled: yes 
      daemon-reload: yes
  - name: install the grafana
    yum:
      name: https://dl.grafana.com/oss/release/grafana-6.2.1-1.x86_64.rpm
      state: present
  - name: Start grafana
    systemd: 
      name: grafana-server
      state: reloaded 
      enabled: yes 
      daemon-reload: yes