global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'codelab-monitor'

rule_files:
scrape_configs:
  - job_name: 'prometheus_metrics'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: "nodes_metrics"
    scrape_interval: "15s"
    static_configs:
    - targets: ['prometheus:9100', 'kafka:9100', 'worker:9100']
  - job_name: "kafka_metrics"
    scrape_interval: "15s"
    static_configs:
    - targets: ['kafka:9308']