---
- hosts: prometheus
  connection: local 
  become: true
  become_method: sudo
  tasks:
  - name: Add host names
    lineinfile:
      dest: /etc/hosts
      line: '{{ item }}'
    with_items:
      - '10.10.0.102 prometheus'
      - '10.10.0.100 kafka'
  - name: Disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: false
  - name: Download node_exporter
    get_url: 
      url: https://github.com/prometheus/node_exporter/releases/download/0.11.0/node_exporter-0.11.0.linux-amd64.tar.gz
      dest: /tmp/node_exporter-0.11.0.linux-amd64.tar.gz
  - name: Create node_exporter directory
    file: 
      path: /opt/node_exporter 
      state: directory
  - name: Unpack node_exporter
    unarchive: 
      src: /tmp/node_exporter-0.11.0.linux-amd64.tar.gz
      dest: /opt/node_exporter
      copy: no
  - name: Node_exporter service file
    copy: 
      src: /vagrant/node_exporter.service 
      dest: /etc/systemd/system/node_exporter.service
      force: yes
  - name: Start node_exporter
    systemd: 
      name: node_exporter
      state: reloaded 
      enabled: yes 
      daemon-reload: yes
  - name: Wait
    wait_for:
      timeout: 15
  - name: Install pip
    yum: 
      name: python-pip 
      state: installed
  - name: Install kafka-python
    pip:
      name: kafka-python