---
- hosts: worker
  connection: local 
  become: true
  become_method: sudo
  tasks:
  - name: Add host names
    lineinfile:
      dest: /etc/hosts
      line: '{{ item }}'
    with_items:
      - '10.10.0.102 prometheus'
      - '10.10.0.100 kafka'
  - name: Disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: false
  - name: Download node_exporter
    get_url: 
      url: https://github.com/prometheus/node_exporter/releases/download/v0.16.0-rc.1/node_exporter-0.16.0-rc.1.linux-amd64.tar.gz
      dest: /tmp/node_exporter-0.16.0-rc.1.linux-amd64.tar.gz
  - name: Create node_exporter directory
    file: 
      path: /opt/node_exporter 
      state: directory
  - name: Unpack node_exporter
    unarchive: 
      src: /tmp/node_exporter-0.16.0-rc.1.linux-amd64.tar.gz
      dest: /opt/node_exporter
      copy: no
      extra_opts: [--strip-components=1]
  - name: Node_exporter service file
    copy: 
      src: /vagrant/node_exporter.service 
      dest: /etc/systemd/system/node_exporter.service
      force: yes
  - name: Start node_exporter
    systemd: 
      name: node_exporter
      state: reloaded 
      enabled: yes 
      daemon-reload: yes
  - name: Wait
    wait_for:
      timeout: 15
  - name: Install pip
    yum: 
      name: python-pip 
      state: installed
  - name: Install kafka-python
    pip:
      name: kafka-python
  - name: Create consumer directory
    file: 
      path: /opt/consumer 
      state: directory
  - name: Consumer script file
    copy: 
      src: /vagrant/consumer.py
      dest: /opt/consumer/consumer.py
      force: yes
  - name: Consumer service file
    copy: 
      src: /vagrant/consumer.service 
      dest: /etc/systemd/system/consumer.service
      force: yes
  - name: Start consumer
    systemd: 
      name: consumer
      state: started 
      daemon-reload: yes
  - name: Create producer directory
    file: 
      path: /opt/producer 
      state: directory
  - name: producer script file
    copy: 
      src: /vagrant/producer.py
      dest: /opt/producer/producer.py
      force: yes
  - name: producer service file
    copy: 
      src: /vagrant/producer.service 
      dest: /etc/systemd/system/producer.service
      force: yes
  - name: Start producer
    systemd: 
      name: producer
      state: started 
      daemon-reload: yes