---
- hosts: kafka
  connection: local 
  become: true
  become_method: sudo
  tasks:
  - name: Add host names
    lineinfile:
      dest: /etc/hosts
      line: '{{ item }}'
    with_items:
      - '10.10.0.101 worker'
      - '10.10.0.102 prometheus'
  - name: Install java
    yum: 
      name: java-1.8.0-openjdk 
      state: installed
  - name: Download kafka
    get_url: 
      url: https://www.apache.org/dist/kafka/2.1.1/kafka_2.11-2.1.1.tgz 
      dest: /tmp/kafka_2.11-2.1.1.tgz
  - name: Create Kafka directory
    file: 
      path: /opt/kafka 
      state: directory
  - name: Unpack
    unarchive: 
      src: /tmp/kafka_2.11-2.1.1.tgz  
      dest: /opt/kafka/
      copy: no 
      extra_opts: [--strip-components=1]
  - name: Zookeeper service file
    copy: 
      src: /vagrant/zookeeper.service 
      dest: /etc/systemd/system/zookeeper.service 
      force: yes
  - name: Kafka service file
    copy: 
      src: /vagrant/kafka.service 
      dest: /etc/systemd/system/kafka.service
      force: yes
  - name: Start Zookeper
    systemd: 
      name: zookeeper
      state: reloaded 
      enabled: yes 
      daemon-reload: yes
  - name: Wait
    wait_for:
      timeout: 30
  - name: Start Kafka
    systemd: 
      name: kafka
      state: reloaded 
      enabled: yes
  - name: Wait
    wait_for:
      timeout: 30
  - name: Disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: false
  - name: Download node_exporter
    get_url: 
      url: https://github.com/prometheus/node_exporter/releases/download/0.11.0/node_exporter-0.11.0.linux-amd64.tar.gz
      dest: /tmp/node_exporter-0.11.0.linux-amd64.tar.gz
  - name: Create node_exporter directory
    file: 
      path: /opt/node_exporter 
      state: directory
  - name: Unpack node_exporter
    unarchive: 
      src: /tmp/node_exporter-0.11.0.linux-amd64.tar.gz
      dest: /opt/node_exporter
      copy: no
  - name: Node_exporter service file
    copy: 
      src: /vagrant/node_exporter.service 
      dest: /etc/systemd/system/node_exporter.service
      force: yes
  - name: Start node_exporter
    systemd: 
      name: node_exporter
      state: reloaded 
      enabled: yes 
      daemon-reload: yes
  - name: Wait
    wait_for:
      timeout: 15
  - name: Disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: false
  - name: Create input topic
    command: "/opt/kafka/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic input"
  - name: Create output topic
    command: "/opt/kafka/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic output"
  - name: Download kafka_exporter
    get_url: 
      url: https://github.com/danielqsj/kafka_exporter/releases/download/v1.2.0/kafka_exporter-1.2.0.linux-amd64.tar.gz
      dest: /tmp/kafka_exporter-1.2.0.linux-amd64.tar.gz
  - name: Create kafka_exporter directory
    file: 
      path: /opt/kafka_exporter 
      state: directory
  - name: Unpack
    unarchive: 
      src: /tmp/kafka_exporter-1.2.0.linux-amd64.tar.gz 
      dest: /opt/kafka_exporter/
      copy: no 
      extra_opts: [--strip-components=1]
  - name: kafka_exporter service file
    copy: 
      src: /vagrant/kafka_exporter.service 
      dest: /etc/systemd/system/kafka_exporter.service 
      force: yes
  - name: Start kafka_exporter
    systemd: 
      name: kafka_exporter
      state: started 
      enabled: yes 
      daemon-reload: yes